version: "3.8"

services:
    postgres_merise:
        image: postgres:16.1
        container_name: postgres_merise
        restart: always
        environment:
            POSTGRES_USER: sarah
            POSTGRES_PASSWORD: Oxymore59230
            POSTGRES_DB: brief_merise
        ports:
            - 9254:5432
        volumes:
            - postgres_brief_merise:/var/lib/postgresql/data/

volumes:
    postgres_brief_merise:
        driver: local
